# This is a basic workflow to help you get started with Actions

name: Login

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install zsh

      # Runs a single command using the runners shell
      - name: Check shell scripts
        run: |
          find . \( -name .git \) -prune -o -type f -exec grep -l -E '^#!.+bash' '{}' \; | xargs -n 1 -I '{}' bash -n "{}"
          find . \( -name .git \) -prune -o -type f -exec grep -l -E '^#!.+zsh' '{}' \; | xargs -n 1 -I '{}' zsh -n "{}"

      - name: Check sudoers
        run: set nullglob visudo --check --strict login/etc/sudoers.d/*

      - name: Systemd unit files
        run: |
          # systemd will check if the executables refered by the service files exist
          sudo cp login/usr/local/bin/* /usr/local/bin/
          cd login/etc/systemd/system/
          # cannot use option `--user` because it throws error "Failed to initialize manager: No such device or address"
          sudo systemd-analyze verify *
